# Generated by Django 3.2 on 2021-04-22 17:46

from django.db import migrations, models
import django.db.models.deletion
import rest_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Data",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("data", rest_api.models.DataField()),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="rest_api.category")),
            ],
        ),
    ]
